language: ruby
ruby:
- 2.2
deploy:
  provider: rubygems
  api_key:
    secure: Z0Deerg7J5cIRIxnnU2AcBe5dj2V/6pj2GoAW6Xr4FKI5ARmVVoObALRFnWLNHyzGRJgougGStisuqt0uzqhz/b/AbNglmbNZkOjOdu+UdQsUVriAtuiMQIxT7d8cVuXXPLrJDr5A/4aDq6s62nyiYMQUotp2R12A6zR7WAbpFznyJrfVTh32U7pgTD4RenN3QfT9Hsq1o0Kz5m5NsobM4Dvbz2DiwAmUmKu+jOiYHzKEcUWJO3DGHdA+ObYQWdYfzJaIp4Kw2mYUYPsR3w50qJMjdML7HXTxI1uDai2Qv1lPDgFZjvfzXOwhnY7c8wtOvl8GqG3fp8yL2PN9jemXbKCqW29SXG7UUTf1tKPA/jZqbZ+GcsAmr1/4B/n5g2dcCeSIr+MR/X6Zd24bEZkfbxw/aH8kxBSd3NBqnLpnYFYFlifGKvxdGgT4OnlNQOdPNetAsxcUokkyW52EbpmK3x1R43iKL1FoNgAdxJKVHc6CmOvtE0mp7y/MvK2OKSJ0+tFg6BjvygO5DrmfRZiRlX7gn1Jp7y+hy7WS/iWuRPbF79TUXxJ13jVK+MK5scguwMeV95ZhrEewWq4ulRPEZ0/fYNlcj1+BJ4uF0fAjLsjMESP8hedguGT2vUJSvOJli6mx0YpyBFTNW8W1c1EgpipMq1UeXZO79US57O37zQ=
  gem: marathon_deploy
  on:
    tags: true
    repo: eBayClassifiedsGroup/marathon_deploy
    all_branches: true
env:
  global:
    secure: 5TDe4PAOoKK3CLw6DKhiUx0gGDpJnVIs0XFLVj4Ndi701vNXeaT0knzwnTKrNSFrN3fCHXjgl/6YpB4cCDaIq+ZPVCmZka/G19EB73SWi3LPMLt8IXTXLL7Vk0sPeEtR2wGv4rgqgmw/NGVPNrQYPkYFoxx+k4be66nCZIsTFFaRJ3/N2cKamOz7spGbgC6TfGGGPP/0HjSF0FV8vFZc3vgwFWmaH2LWTmGX/aQe7qW9aW1ESN6u8E2O499PpmB5+c5PFknTTJBw4khTIT5TwCA3hPdOYksibuPP/0QcPb7Tf9GEbYnVECihVFC9lGm7CPEOQdtx3FTUHCUJN49SJE1tSlTctuB5nxZ9eqfFNfvFD5YPpymsCOXNbjOEEIr3kxsGlqJEiH4+IG3HV7+jo9NBrSYOp9HxQcSQRcv5t8geyfmcRmi0j5+o/TQ0UUaIRN6uVfevoKmCW7k2Eu1PDWvxrUlkmToxptFj6BIYahBlwveMqdQoOhuSO4CFU85MwvyI8nMBro5mzOiy5TXhaQiZ+4KyLvUyyKmW7/O9HDSsoYjNImgDvzGD0XJOWqeHdDlaf/NA+QwbVFmSHiErUQ4KPTF0JqpUa680iORP9HRUTL79dNfK25Bx+51KMdhr87KRkUE3gRNl0mJ5Zgnba+jOeds8t64hGE6J+n4WSGc=
